// Generated by CoffeeScript 1.8.0
var hamburger, header_info;

if ($('.header-info').length > 0) {
  header_info = $('.header-info');
  hamburger = $('.hamburger');
  $(document).scroll(function() {
    if ($(document).scrollTop() >= 50) {
      return hamburger.addClass("show");
    } else {
      return hamburger.removeClass("show");
    }
  });
}
