// Generated by CoffeeScript 1.8.0
var header, header_height, header_info;

if ($('html').length > 0) {
  header = $('header');
  header_info = $('.header-info');
  header_height = header.height();
  header_info.css("margin-top", -header_height);
  $(window).on('resize', function() {});
  header_height = header.height();
}
