// Generated by CoffeeScript 1.8.0
var closer, hamburger, header, nav;

if ($('nav').length > 0) {
  hamburger = $('.hamburger');
  closer = $('.closer');
  nav = $('nav');
  header = $('header');
  hamburger.click(function() {
    header.addClass("menu-active");
    return nav.addClass("menu-active");
  });
  closer.click(function() {
    header.removeClass("menu-active");
    return nav.removeClass("menu-active");
  });
}
