// Generated by CoffeeScript 1.8.0
var hamburger, info, info_height;

if ($('.hamburger').length > 0) {
  info = $('.header-info');
  hamburger = $('.hamburger');
  info_height = info.height();
  $(document).scroll(function() {
    if ($(document).scrollTop() >= info_height + 30) {
      return hamburger.addClass("show");
    } else {
      return hamburger.removeClass("show");
    }
  });
}
