// Generated by CoffeeScript 1.8.0
var closer, container, hamburger, header, nav;

if ($('nav').length > 0) {
  hamburger = $('.hamburger');
  closer = $('.closer');
  nav = $('nav');
  header = $('header');
  container = $('#container');
  hamburger.click(function() {
    container.prepend("<div class='overlay'></div>");
    header.addClass("menu-active");
    return nav.addClass("menu-active");
  });
  closer.click(function() {
    var overlay;
    overlay = $('.overlay');
    overlay.remove();
    header.removeClass("menu-active");
    return nav.removeClass("menu-active");
  });
  container.click(function() {
    var overlay;
    overlay = $('.overlay');
    overlay.remove();
    header.removeClass("menu-active");
    return nav.removeClass("menu-active");
  });
}
